version : '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 8081:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatlog:4000
      - CURRENCY_SERVICE_ADDR=currency:9001
      - CART_SERVICE_ADDR=cart:80
      - RECOMMENDATION_SERVICE_ADDR=recommended:8082
      - CHECKOUT_SERVICE_ADDR=checkout:5050
      - SHIPPING_SERVICE_ADDR=shipping:5551
      - AD_SERVICE_ADDR=ad:9555
      - PORT=8081
      - OTLP_FORMAT=$OTLP_FORMAT
      - OTLP_ENDPOINT=$OTLP_ENDPOINT
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=FRONTENDSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES

    depends_on:
      - currency
      - cart
      - productcatlog
      - recommended
  cart:
    build: ./cartservice
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OTLP_ENDPOINT=$OTLP_ENDPOINT
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=CARTSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - OTLP_FORMAT=$OTLP_FORMAT
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES


  currency:
    build: ./currencyservice
    ports:
      - 9001:9001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=9001
      - OTLP_ENDPOINT=$OTLP_ENDPOINT
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=CURENCYSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - OTLP_FORMAT=$OTLP_FORMAT
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS

  recommended:
    build: ./recommendationservice
    ports:
      - 8082:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=8082
      - OTLP_ENDPOINT=$OTLP_ENDPOINT
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=RECOMMENDATIONSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatlog:4000
      - OTLP_FORMAT=$OTLP_FORMAT   
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES

    depends_on:
      - cart
      - currency
  productcatlog:
    build: ./productcatalogservice
    ports:
      - 4000:4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=4000
      - OTLP_FORMAT=$OTLP_FORMAT
      - OTLP_ENDPOINT=$OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=PRODUCTCATLOGSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES

    depends_on:
      - cart
      - recommended
      - currency
  checkout:
    build: ./checkoutservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports: 
      - 5050:5050
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatlog:4000
      - CURRENCY_SERVICE_ADDR=currency:9001
      - CART_SERVICE_ADDR=cart:80
      - RECOMMENDATION_SERVICE_ADDR=recommended:8082
      - EMAIL_SERVICE_ADDR=email:4009
      - SHIPPING_SERVICE_ADDR=shipping:5551
      - PAYMENT_SERVICE_ADDR=payment:8011
      - AD_SERVICE_ADDR=ad:9555
      - PORT=5050
      - OTLP_FORMAT=$OTLP_FORMAT
      - OTLP_ENDPOINT=$OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=CHECKOUTSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES

    depends_on:
      - frontend
      - cart
      - currency
  payment:
    build: ./paymentservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8011:8011
    environment:
      - PORT=8011
      - OTLP_ENDPOINT=$OTLP_ENDPOINT
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=PAYMENTSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - OTLP_FORMAT=$OTLP_FORMAT
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES
    depends_on:
      - checkout
      - currency
  shipping:
    build: ./shippingservice
    ports:
      - 5551:5551
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=5551
      - OTLP_FORMAT=$OTLP_FORMAT
      - OTLP_ENDPOINT=$OTLP_ENDPOINT
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=SHIPPINGSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES

    depends_on:
      - frontend
      - cart
      - currency
      - checkout
  ad:
    build: ./adservice
    ports:
      - 9555:9555
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - EXPORTER_ENDPOINT="YOUR_EXPORTER_ENDPOINT"
      - EXPORT_TYPE=otlp
      - SERVICE_NAME=ADSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS
      - OTLP_PROTOCOL=http/protobuf
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES

    depends_on:
      - checkout
  email:
    build: ./emailservice
    ports:
      - 4009:4009
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - checkout
    environment:
      - OTLP_ENDPOINT=$OTLP_ENDPOINT
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=EMAILSERVICE
      - SERVICE_NAMESPACE=$SERVICE_NAMESPACE
      - OTLP_FORMAT=$OTLP_FORMAT
      - USER=""
      - PASSWORD="" 
      - OTEL_EXPORTER_OTLP_HEADERS=$OTEL_EXPORTER_OTLP_HEADERS
      - OTEL_RESOURCE_ATTRIBUTES=$OTEL_RESOURCE_ATTRIBUTES


# For sending traces to localhost use endpoint http://host.docker.internal:4317