version : '3'
services:
  frontend:
    build: ./frontend
    ports:
      - 8081:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatlog:4000
      - CURRENCY_SERVICE_ADDR=currency:9001
      - CART_SERVICE_ADDR=cart:80
      - RECOMMENDATION_SERVICE_ADDR=recommended:8082
      - CHECKOUT_SERVICE_ADDR=checkout:5050
      - SHIPPING_SERVICE_ADDR=shipping:5551
      - AD_SERVICE_ADDR=ad:9555
      - PORT=8081
      - OTLP_ENDPOINT=host.docker.internal:4317
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=FRONTENDSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - OTLP_FORMAT="HTTP"
    depends_on:
      - currency
      - cart
      - productcatlog
      - recommended
  cart:
    build: ./cartservice
    ports:
      - 80:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OTLP_ENDPOINT=http://host.docker.internal:4317
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=CARTSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - OTLP_FORMAT="HTTP"
  currency:
    build: ./currencyservice
    ports:
      - 9001:9001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=9001
      - OTLP_ENDPOINT=http://host.docker.internal:4317
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=CURENCYSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - OTLP_FORMAT="HTTP"
  recommended:
    build: ./recommendationservice
    ports:
      - 8082:8082
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=8082
      - OTLP_ENDPOINT=http://host.docker.internal:55681/v1/traces
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=AD_RECOMMENDATIONSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatlog:4000
      - OTLP_FORMAT="HTTP"   
      - USER=""
      - PASSWORD=""
      - OTEL_EXPORTER_OTLP_HEADERS={"Authorization":"Bearer bearer_token"}
      - OTLP_HEADERS={"Authorization":"Bearer bearer_token"}
    depends_on:
      - cart
      - currency
  productcatlog:
    build: ./productcatalogservice
    ports:
      - 4000:4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=4000
      - OTLP_ENDPOINT=host.docker.internal:4317
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=PRODUCTCATLOGSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - OTLP_FORMAT="HTTP"     
    depends_on:
      - cart
      - recommended
      - currency
  checkout:
    build: ./checkoutservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports: 
      - 5050:5050
    environment:
      - PRODUCT_CATALOG_SERVICE_ADDR=productcatlog:4000
      - CURRENCY_SERVICE_ADDR=currency:9001
      - CART_SERVICE_ADDR=cart:80
      - RECOMMENDATION_SERVICE_ADDR=recommended:8082
      - EMAIL_SERVICE_ADDR=email:4009
      - SHIPPING_SERVICE_ADDR=shipping:5551
      - PAYMENT_SERVICE_ADDR=payment:8011
      - AD_SERVICE_ADDR=ad:9555
      - PORT=5050
      - OTLP_ENDPOINT=host.docker.internal:4317
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=CHECKOUTSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - OTLP_FORMAT="HTTP"     
    depends_on:
      - frontend
      - cart
      - currency
  payment:
    build: ./paymentservice
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8011:8011
    environment:
      - PORT=8011
      - OTLP_ENDPOINT=http://host.docker.internal:4317
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=PAYMENTSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - OTLP_FORMAT="HTTP" 
    depends_on:
      - checkout
      - currency
  shipping:
    build: ./shippingservice
    ports:
      - 5551:5551
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PORT=5551
      - OTLP_ENDPOINT=host.docker.internal:4317
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=SHIPPINGSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - OTLP_FORMAT="HTTP"    
    depends_on:
      - frontend
      - cart
      - currency
      - checkout
  ad:
    build: ./adservice
    ports:
      - 9555:9555
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OTLP_ENDPOINT=host.docker.internal:4317
      - EXPORTER="otlp"
      - SERVICE_NAME=ADSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - OTLP_FORMAT="HTTP" 
    depends_on:
      - checkout
  email:
    build: ./emailservice
    ports:
      - 4009:4009
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - checkout
    environment:
      - OTLP_ENDPOINT=http://host.docker.internal:55681/v1/traces
      - EXPORTER="otlp"
      - EXPORT_TYPE=OTLP
      - SERVICE_NAME=AD_EMAILSERVICE
      - SERVICE_NAMESPACE=LM_HIPSTER
      - OTLP_FORMAT="HTTP"
      - USER=""
      - PASSWORD="" 
      - OTEL_EXPORTER_OTLP_HEADERS={"Authorization":"Bearer bearer_token"}
      - OTLP_HEADERS={"Authorization":"Bearer bearer_token"}
